### ISSUE TITLE
Icospheres 6,7,8

### ISSUE THREAD

**Issue by lukem12345** [AlgebraicJulia/Decapodes.jl#108]
Now that we generate more efficient programs, we are able to run simulations on meshes with very fine resolution.

We should provide meshes of the icosphere of 6,7, and 8 subdivisions.

We should probably also provide a rectangular mesh of finer resolution. (Or perhaps some helper script to do so on-demand.)

**Comment by quffaro** [comment]
[I've added 6, 7, 8 here](https://github.com/AlgebraicJulia/DecapodesMeshes.jl/pull/1)

**Comment by lukem12345** [comment]
Closed by https://github.com/AlgebraicJulia/CombinatorialSpaces.jl/pull/79
