### ISSUE TITLE
Docs for Debugging

### ISSUE THREAD

**Issue by jpfairbanks** [AlgebraicJulia/Decapodes.jl#133]
The PR #128 removed some docs on how to debug a simulation. This should be restored sooner rather than later.

**Comment by lukem12345** [comment]
A few docs changes are currently sitting in the backlog, like this one. I want to address them in 1 issue & PR duo to reduce overhead and start-stop delays.

Changes to make:
- [ ] This issue
- [ ] Add Klausmeier model docs page
- [ ] Add CISM benchmark page
- [ ] Update README (especially important for first impressions)
- [ ] Spruce up the 1D Poiseuille doc
