### ISSUE TITLE
ASCII Support

### ISSUE THREAD

**Issue by lukem12345** [AlgebraicJulia/Decapodes.jl#138]
Currently, the main way that users create Decapodes is via the `@decapode` macro. The `@decapode` macro requires users to specify tangent variables via a special operator `\partial\_t`. This is fine in environments where users have an easy way of writing Unicode characters.

However, Unicode support cannot be considered universal over all possible editors that a user may wish to use.

So, we should offer ASCII versions of special characters like `\partial\_t` that behave exactly like their Unicode counterparts.

**Comment by jpfairbanks** [comment]
We probably need at least, 

1. `partial_t`
2. `div`
3. `grad`
4. `curl`
5. `lie`
6. `lapl`
7. `wedge`
8. `dual_d`
9. `star`
10. `star_inv`

Anything else?

Should `partial_t` be an alias for a function `partial(u, x)` that represents the partial derivative of `u` wrt the dimension `x`?

**Comment by lukem12345** [comment]
I am somewhat inclined to offer just one "derivative" symbol `d` such that:
- unary `d(X)` is the exterior derivative
- binary `d(X,Y)` is the Lie derivative / generalization of directional derivative / generalization of partial derivative
- binary `d(X,t)` is the derivative w.r.t. t

However, not sure which level of the current stack would be responsible for catching `t`. This is further complicated by the fact that `t` may itself be a `Parameter` that returns the current time. Many ways of addressing this I believe...
