### ISSUE TITLE
Adding an Alias table to Decapode ACSet Schema

### ISSUE THREAD

**Issue by jpfairbanks** [AlgebraicJulia/Decapodes.jl#155]
When you have a decapode with equations like this:

```julia
dexp = parse_decapode(quote
  A::Form0{X}
  B::Form1{X}
  C::Form0{X}
  D::Form0{X}

  B == grad(A)
  C == f(A,B)
  ∂ₜ(A) == C
  ∂ₜ(D) == C + D
end)
```

Our current code will eliminate the variable `C` and by renaming it to `A\dot`. We probably need another table of aliases that is just a binary relation on `Var` for tracking equations between variables.

@olynch, does the GATLab approach solve this problem in a more general way?

**Comment by lukem12345** [comment]
Did we not fix this in https://github.com/AlgebraicJulia/Decapodes.jl/pull/136 ?

Not at a REPL now, so I cannot check this.

**Comment by lukem12345** [comment]
This is the test I am referring to:
https://github.com/AlgebraicJulia/Decapodes.jl/blob/c204376132f0e6324434341530f096409ec03a1d/test/diag2dwd.jl#L225

**Comment by jpfairbanks** [comment]
I ran into this problem when building the DecaExpr outside of `parse_decapode` or `@decapode`. There might be something about how I am generating the `DecaExpr`.

**Comment by lukem12345** [comment]
I see. I will check in the morning on where `dot_rename!` may be erroneously getting called.
