### ISSUE TITLE
Aqua.jl Report

### ISSUE THREAD

**Issue by quffaro** [AlgebraicJulia/Decapodes.jl#213]
![Aqua.jl](https://github.com/AlgebraicJulia/Decapodes.jl/assets/22090069/a945e10f-7a42-4f9e-8cb1-cbb1d569d811)

The attached image is a screencap from the latest Aqua.jl run after suppressing ambiguities.

**Comment by lukem12345** [comment]
Where would `Decapodes.AppCirc2` be coming from?
