### ISSUE TITLE
Is Brusselator definition correct

### ISSUE THREAD

**Issue by quffaro** [AlgebraicJulia/Decapodes.jl#214]
https://github.com/AlgebraicJulia/Decapodes.jl/blob/2de6fae37c59e6b91db81281eb76b141a1755d79/examples/chemistry/brusselator.jl#L37C2-L37C37

@jpfairbanks and I noticed that $\dot{V}$ is dependent on $\Delta(V)$, not $\Delta(U)$. Is this correct?

**Comment by lukem12345** [comment]
Yes the same change made in [this commit](https://github.com/AlgebraicJulia/Decapodes.jl/pull/114/commits/bf3667d8cd0ca03ab968c90b3b010d3f767eb38d) needs to be made here. Go ahead and commit to main.
