### ISSUE TITLE
Index doc page not displaying image 

### ISSUE THREAD

**Issue by GeorgeR227** [AlgebraicJulia/Decapodes.jl#238]
It currently links to Decapodes.jl/dev url but this should either be a pre-rendered image/gif or use a directory path instead to the image instead.

**Comment by lukem12345** [comment]
I made a commit 45ebad to main as a quick fix to use the new url. I would have to do a local build to verify the local ref to use.

**Comment by GeorgeR227** [comment]
You can comment out the pages you don't want to build locally. I think just `index.md`, `ice_dynamics.md` and `grigoriev.md` is enough.

**Comment by GeorgeR227** [comment]
I actually think the local ref is just the `grigoriev/grigoriev.gif` without the rest of the url but I'm building locally now to confirm.

**Comment by GeorgeR227** [comment]
It works and I made a PR for that.
