### ISSUE TITLE
"u" and "p" variable shadowing in Decapodes

### ISSUE THREAD

**Issue by quffaro** [AlgebraicJulia/Decapodes.jl#273]
Currently a variable "u" or "p" variable in a Decapode will shadow the `u` or `p` arrays produced from `gensim`. This prevents further variables or parameters from being indexed.

A solution would probably be to use `gensym` in `gensim`

**Comment by lukem12345** [comment]
I don't want all local variables to be replaced with `gensym`'d names because this hampers readability when debugging code.

**Comment by quffaro** [comment]
I think the "u" and "p" input can be copied to a gensymmed variables?
![image](https://github.com/user-attachments/assets/d39e6e90-eff5-44ac-b7ba-22bf8d26428c)

**Comment by lukem12345** [comment]
Yes just u and p

**Comment by jpfairbanks** [comment]
Would be better to just change the arguments to f(du,u,p,t) to `_du,_u,_p,_t`?

**Comment by quffaro** [comment]
Yeah I've changed them to be `__u__`, etc. Testing locally
