### ISSUE TITLE
Provide Meshes with Artifacts mechanism

### ISSUE THREAD

**Issue by jpfairbanks** [AlgebraicJulia/Decapodes.jl#58]
The Julia Package Manager supports data dependencies like our mesh files using the Artifacts system described in the docs: https://pkgdocs.julialang.org/v1/artifacts/.

It would be good to supply all the mesh objects as OBJ files on a server.

**Comment by lukem12345** [comment]
@jpfairbanks For sphere artifacts should we also include the "unit" version of that artifact?

1. Unit icosphere
2. Icosphere \@ radius = 6371+90
3. Unit TIE-GCM grid
4. TIE-GCM grid \@ radius = 6371+90

Which of 1,2,3,4 should be artifacts?

**Comment by jpfairbanks** [comment]
Yeah, we should have all 4

**Comment by jpfairbanks** [comment]
Just thinking about hosting, we could put them in a git repo AlgebraicJulia/Decapodes-Meshes and then serve them from there. We should also move the meshes from the current locations in docs and test to that storage too.

**Comment by lukem12345** [comment]
Each of the meshes is available as a `.obj` in the repo `DecapodesMeshes.jl`. There is also a tarball containing all 4 of these meshes. This tarball is what is downloaded and unpacked when you use `artifact"all_meshes"` in the `llm/artifacts` branch.

**Comment by jpfairbanks** [comment]
@lukem12345, we need to get a PR for Decapodes that exports

```julia
abstract AbstractMeshKey end
struct UnitIcosphere end
struct ThermoIcosphere end
struct UnitUVSphere end
struct ThermoUVSphere end

loadmesh(meshkey::AbstractMeshKey)::EmbededDeltaSet2D
```

then you would load them with 

```julia
m = loadmesh(ThermoIcosphere)
```

the unit tests would test that all the spheres load and have the right number of triangles, edges, and vertices.

**Comment by jpfairbanks** [comment]
The reason to use singleton types and dispatch is so that people can make new packages that export their own meshes by adding methods to loadmesh, rather than by editing a case statement in Decapodes.jl
