### ISSUE TITLE
Serializing Outputs as JLD2 files

### ISSUE THREAD

**Issue by jpfairbanks** [AlgebraicJulia/Decapodes.jl#91]
We should support serializing the output of the solvers to a stable serialization format. JLD2 would be a good candidate.

**Comment by lukem12345** [comment]
The current practice is to use `JLD2.@save` to save the simulation results, so this issue is technically closed.

More "structured" means of saving (and loading) data is encompassed by simulation-pipeline work with @olynch and @quffaro .
