### ISSUE TITLE
Create a tag?

### ISSUE THREAD

**Issue by ChrisRackauckas** [AlgebraicJulia/Decapodes.jl#99]
There have been 114 commits to main since the last tag. Now that we will be building off of this, it would be good for this library to start to follow a documented continuous release process and semver

**Comment by ChrisRackauckas** [comment]
Master is failing.

Also, most of the packages do not have a compat entry: https://github.com/AlgebraicJulia/Decapodes.jl/blob/main/Project.toml#L7-L29

**Comment by jpfairbanks** [comment]
I'm glad to hear that you are planning to build on Decapodes. We can certainly get these issues resolved. 

@mehalter, @lukem12345
